# Generated by Django 3.0.7 on 2020-06-09 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tpo.models.listening
import tpo.models.speaking
import tpo.models.writing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening', models.FileField(upload_to=tpo.models.listening.upload_location_listening)),
                ('listening_image', models.FileField(upload_to=tpo.models.listening.upload_location_listening)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(default='Conversation', max_length=30)),
                ('phase', models.IntegerField(blank=True, null=True)),
                ('related', models.CharField(blank=True, max_length=500, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.CharField(default='', max_length=200)),
                ('phase', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(default=' ', max_length=200)),
                ('passage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Speaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.CharField(blank=True, max_length=200, null=True)),
                ('speaking_audio_file', models.FileField(blank=True, null=True, upload_to=tpo.models.speaking.upload_location_speaking)),
                ('speaking_reading_title', models.CharField(blank=True, max_length=400, null=True)),
                ('speaking_reading', models.TextField(blank=True, null=True)),
                ('speaking_image', models.FileField(blank=True, null=True, upload_to=tpo.models.speaking.upload_location_speaking)),
                ('speaking_question', models.TextField()),
                ('speaking_question_audio_file', models.FileField(blank=True, null=True, upload_to=tpo.models.speaking.upload_location_speaking)),
                ('speaking_question_guide_audio_file', models.FileField(blank=True, null=True, upload_to=tpo.models.speaking.upload_location_speaking)),
                ('speaking_question_before_read_audio', models.FileField(blank=True, null=True, upload_to=tpo.models.speaking.upload_location_speaking)),
                ('number', models.IntegerField()),
                ('speaking_audio_file_transcript', models.TextField(blank=True, null=True)),
                ('sections', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('mode', models.CharField(choices=[('T', 'TPO'), ('M', 'Mock'), ('A', 'Assignment'), ('P', 'Practice')], default='M', max_length=1)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('reading_time', models.IntegerField(blank=True, null=True)),
                ('class_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.Class')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.CharField(blank=True, max_length=200, null=True)),
                ('writing_listening', models.FileField(blank=True, null=True, upload_to=tpo.models.writing.upload_location_writing)),
                ('writing_image', models.FileField(blank=True, null=True, upload_to=tpo.models.writing.upload_location_writing)),
                ('writing_reading', models.TextField(blank=True, null=True)),
                ('writing_question', models.TextField()),
                ('type', models.CharField(default='Independent', max_length=30)),
                ('writing_listening_transcript', models.TextField(blank=True, null=True)),
                ('section', models.IntegerField(default=1)),
                ('sections', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WritingTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('time', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestWriting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Test')),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Writing')),
            ],
        ),
        migrations.CreateModel(
            name='TestSpeaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Speaking')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField(default=0)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Reading')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestListening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField(default=0)),
                ('listening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Listening')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Test')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('preparation_time', models.IntegerField()),
                ('answering_time', models.IntegerField()),
                ('reading_time', models.IntegerField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Test')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('insertion_sentence', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField()),
                ('related_paragraph', models.IntegerField(blank=True, null=True)),
                ('related_passage', models.TextField(blank=True, null=True)),
                ('related_passage_title', models.CharField(blank=True, max_length=400, null=True)),
                ('question_type', models.CharField(max_length=10)),
                ('right_answer', models.CharField(max_length=50)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Reading')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('code', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.ReadingQuestions')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('time', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Test')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('listening_question_audio_file', models.FileField(upload_to=tpo.models.listening.upload_location_listening_questions)),
                ('number', models.IntegerField()),
                ('quote', models.BooleanField(default=False)),
                ('quote_audio_file', models.FileField(blank=True, null=True, upload_to=tpo.models.listening.upload_location_listening_questions)),
                ('right_answer', models.CharField(max_length=50)),
                ('listening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Listening')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('code', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.ListeningQuestions')),
            ],
        ),
    ]
