# Generated by Django 3.0.7 on 2020-07-24 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tpo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningquestions',
            name='right_answer',
        ),
        migrations.RemoveField(
            model_name='readingquestions',
            name='right_answer',
        ),
        migrations.AlterField(
            model_name='test',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='mode',
            field=models.CharField(choices=[('T', 'TPO'), ('M', 'Mock'), ('A', 'Assignment'), ('P', 'Practice')], default='T', max_length=1),
        ),
        migrations.CreateModel(
            name='ReadingQuestionCorrectAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.ReadingAnswers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.ReadingQuestions')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestionCorrectAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.ListeningAnswers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.ListeningQuestions')),
            ],
        ),
    ]
