# Generated by Django 3.0.7 on 2020-06-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20200609_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'corrector'), (4, 'institute'), (5, 'admin')], default=5),
        ),
    ]
